### ISSUE TITLE
These options for the template url don't work

### ISSUE THREAD

**Issue by tantv** [DiemenDesign/summernote-templates#1]
Hi @DiemenDesign,

Thank you for the great plugin I cloned it and it's work correct with URL default.
But if I don't put the template URL as the option it's only got the URL default
Can you help me check it? This is my code

```javascript
$('textarea').summernote({
    toolbar: [
      ['custom',['pageTemplates','blocks']],
       ['style', ['style']],
       ['font', ['bold', 'italic', 'underline']]
   templates: {
      templates: 'URL/page-templates/'
   },
   blocks: {
      templates: 'URL/blocks-templates/'
   }
});
```

**Comment by DennisSuitters** [comment]
Use the templates like you would for traversing folders, it won't work cross domain.

**Comment by tantv** [comment]
Hi @DiemenDesign,

I think the line **var options   = context.options;** work incorrect with the data passed to the option:

```javascript
$('textarea').summernote({
    toolbar: [
      ['custom',['pageTemplates','blocks']],
       ['style', ['style']],
       ['font', ['bold', 'italic', 'underline']]
   templates: {
      templates: 'URL/page-templates/'
   },
   blocks: {
      templates: 'URL/blocks-templates/'
   }
});
```
You can **console.log(options);** and you will see two keys will show in the console:
**pageTemplates**: with all default values
**templates**: with these custom values

So when you get template with this line **$.get(options.pageTemplates.templates)** it will work incorrectly with the custom folder

Please let me know if I misunderstand something.

Thanks,

**Comment by DennisSuitters** [comment]
`var options = context.options;` is correct, it's one of the ways of getting Summernote data into the plugin, and for getting the extended vars for options that are set before hand.

**Comment by FabrizioC** [comment]
HI @tantv,

try this:
```
$('textarea').summernote({
    toolbar: [
      ['custom',['pageTemplates','blocks']],
       ['style', ['style']],
       ['font', ['bold', 'italic', 'underline']]
   pageTemplates: {
      templates: 'URL/page-templates/'
   },
   blocks: {
      templates: 'URL/blocks-templates/'
   }
});
```
to use a custom path, but as I note this overwrite all settings (icons too)

**Comment by tantv** [comment]
Hi @FabrizioC,

The first time I configured as your suggestions and I need must override too much so I edited the core file and it works correctly as I expected
Thanks for your help.
I will close ticket now.

Regards,
Tan Truong

**Comment by FabrizioC** [comment]
Hi @tantv,
can you show me your solution, please?
Thanks,
Fabrizio

**Comment by DennisSuitters** [comment]
You can also set the options directly in the plugin. I'm guessing they've changed the example `URL` part to an actual url.

**Comment by tantv** [comment]
Hi @FabrizioC,

Because I want to build a builder based on the plugin so I custom too much the plugin's @DiemenDesign - I have about 300 blocks with 300 image examples
And here what I changed:
```javascript
srcPageTemplates: {
  templates: 'URL/page-templates/'
},
srcBlockTemplates: {
  templates: 'URL/blocks-templates/'
}
```
Then I go to the core file and replace **options.blocks.templates** with **options.srcBlockTemplates.templates** (same with the **srcPageTemplates**)
These changes will keep all settings from the core and I only just update the correct URL for my custom

Regards,
Tan Truong

**Comment by DennisSuitters** [comment]
If your up to it, it would be awesome to share your updates, esp. if it improves the plugin.

**Comment by FabrizioC** [comment]
Hi @tantv,
thanks for sharing
