### ISSUE TITLE
What is it??

### ISSUE THREAD

**Issue by devangelfish** [DiemenDesign/summernote-templates#5]
server request url like this 

 http://localhost:81/summernote-templates/page-templates//summernote-templates/page-templates/resume.png

what's wrong?

**Comment by DennisSuitters** [comment]
Not sure what your trying to do, but I just checked, and the plugin for Summernote works perfectly fine for me.

**Comment by devangelfish** [comment]
![problem](https://user-images.githubusercontent.com/75592835/123931522-8b161200-d9cb-11eb-9a37-fdee95fc593d.PNG)
like this

**Comment by devangelfish** [comment]
![error](https://user-images.githubusercontent.com/75592835/123932809-c36a2000-d9cc-11eb-9365-ceff3838e0f3.PNG)
this is error 

![창1](https://user-images.githubusercontent.com/75592835/123933076-fe6c5380-d9cc-11eb-88b0-99f0ab6bab9a.PNG)
![창2](https://user-images.githubusercontent.com/75592835/123933090-01674400-d9cd-11eb-86eb-649c6c95285b.PNG)
my local directory

![코드](https://user-images.githubusercontent.com/75592835/123933150-104df680-d9cd-11eb-9779-e4f209f3b52c.PNG)
my summernote setting

**Comment by DennisSuitters** [comment]
hm, I'm not sure why it's not working for you, it works as it is for me. The only thing I can think of is how (it looks like your using WIndows) Windows references files. I use Linux, and as I've already said, it works fine for me.

**Comment by devangelfish** [comment]
> hm, I'm not sure why it's not working for you, it works as it is for me. The only thing I can think of is how (it looks like your using WIndows) Windows references files. I use Linux, and as I've already said, it works fine for me.

thanks for reply, It helped for me
